import type { Metadata } from "next";
import { inter } from '@/fonts'
import "./globals.css";

//TODO:Gather information for the title and description from client
//TODO: Need Favicon.ico file
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
